# Constanta declaration
MANGA_SOURCE_MANGADEX = 'mangadex'

MANGA_SOURCE_SELECTION = [
    (MANGA_SOURCE_MANGADEX, 'Mangadex'),
]

ATTRIBUTE_TYPE_TAG = 'tag'
ATTRIBUTE_TYPE_TITTLE = 'title'
ATTRIBUTE_TYPE_DESCRIPTION = 'desc'

ATTRIBUTES_TYPE_SELECTION = [
    (ATTRIBUTE_TYPE_TAG, 'Tag'),
    (ATTRIBUTE_TYPE_TITTLE, 'Title'),
    (ATTRIBUTE_TYPE_DESCRIPTION, 'Description'),
]

STATE_HIATUS = 'hiatus'
STATE_ONGOING = 'ongoing'
STATE_COMPLETED = 'completed'
STATE_CANCELLED = 'cancelled'

MANGA_STATES_SELECTION = [
    (STATE_HIATUS, 'Hiatus'),
    (STATE_ONGOING, 'Ongoing'),
    (STATE_COMPLETED, 'Completed'),
    (STATE_CANCELLED, 'Cancelled'),
]

CONTENT_RATING_SAFE = 'safe'
CONTENT_RATING_MATURE = 'mature'

CONTENT_RATING_SELECTION = [
    (CONTENT_RATING_SAFE, 'Safe'),
    (CONTENT_RATING_MATURE, 'Mature'),
]