# Constanta declaration
MANGA_SOURCE_MANAGEDEX = 'mangadex'

MANGA_SOURCE_SELECTION = [
    (MANGA_SOURCE_MANAGEDEX, 'Mangadex'),
]

ATTRIBUTE_TYPE_TAG = 'tag'
ATTRIBUTE_TYPE_TITTLE = 'title'
ATTRIBUTE_TYPE_DESCRIPTION = 'desc'

ATTRIBUTES_TYPE_SELECTION = [
    (ATTRIBUTE_TYPE_TAG, 'Tag'),
    (ATTRIBUTE_TYPE_TITTLE, 'Title'),
    (ATTRIBUTE_TYPE_DESCRIPTION, 'Description'),
]